
elasticsearch:
  # Deploy an elasticsearch cluster.
  enabled: true
  # Make it a single node cluster
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

# Elasticsearch uri, do not change.
es:
  endpoints:
    - http://graviteeio-apim-elasticsearch-master-hl.gravitee.svc.cluster.local:9200

mongodb:
  # Deploy a mongoDB cluster.
  enabled: true
  # Use a mongoDB image that supports latest Mac chips.
  image:
    repository: mongo
    tag: 6.0.4-jammy
  # Make it a single node cluster
  architecture: standalone
  persistence:
    mountPath: /data/db

# MongoDB uri, do not change.
mongo:
  uri: mongodb://graviteeio-apim-mongodb-replicaset.gravitee.svc.cluster.local/gravitee?connectTimeoutMS=30000

smtp:
  enabled: false

# Change the ingress host with your host domain.
# no TLS provided here. Check the documentation if needed.
api:
  env:
    - name: gravitee_jwt_cookiesecure
      value: "true"
    - name: gravitee_jwt_cookiepath
      value: "/; SameSite=None"
  ingress:
    # tls:
    #   - secretName: console-example-com-tls
    #     hosts:
    #       - management-api.example.com
    management:
      hosts:
        - management-api.example.com
      scheme: https
    portal:
      hosts:
        - management-api.example.com
      scheme: https

# Change the ingress host with your host domain.
# no TLS provided here. Check the documentation if needed.
gateway:
  # replicaCount: 2
  # autoscaling:
  #     enabled: false
  ingress:
    # tls:
    #   hosts:
    #     - gateway.example.com
    #   secretName: console-example-com-tls
    hosts:
      - gateway.example.com
  services:
    sync:
      kubernetes:
        enabled: true
  # sharding_tags: shardingtag1
  # dbLess: true  

# Change the ingress host with your host domain.
# no TLS provided here. Check the documentation if needed.
portal:
  ingress:
    hosts:
      - portal.example.com

# Change the ingress host with your host domain.
# no TLS provided here. Check the documentation if needed.
ui:
  ingress:
    path: /
    hosts:
      - console.example.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    # tls:
    #   - secretName: console-example-com-tls
    #     hosts:
    #       - console.example.com
        