apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: required-for-kustomize-but-not-used
spec:
  plans:
  - name: "Common keyless plan"
    description: "Common keyless for all production APIs"
    security: "KEYLESS"
    status: "PUBLISHED"