
elasticsearch:
  # Deploy an elasticsearch cluster.
  enabled: true
  # Make it a single node cluster
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

# Elasticsearch uri, do not change.
es:
  endpoints:
    - http://graviteeio-apim-elasticsearch-master-hl.gravitee.svc.cluster.local:9200

mongodb:
  # Deploy a mongoDB cluster.
  enabled: true
  # Use a mongoDB image that supports latest Mac chips.
  image:
    repository: mongo
    tag: 6.0.4-jammy
  # Make it a single node cluster
  architecture: standalone
  persistence:
    mountPath: /data/db

# MongoDB uri, do not change.
mongo:
  uri: mongodb://graviteeio-apim-mongodb-replicaset.gravitee.svc.cluster.local/gravitee?connectTimeoutMS=30000

gateway:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /gateway/?(.*)