api:
  enabled: false

portal:
  enabled: false

ui:
  enabled: false

es:
  enabled: false

gateway:
  replicaCount: 1
  autoscaling:
    enabled: false
  ingress:
    enabled: true
  services:
    sync:
      kubernetes:
        enabled: true
  dbLess: true
  reporters:
    elasticsearch:
      enabled: false